name:                hask-can-weather
version:             0.1.0.0
github:              "tvieregge/hask-can-weather"
license:             BSD3
author:              "Tim Vieregge"
maintainer:          "t.vieregge@protonmail.com"
copyright:           "2019 Tim Vieregge"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tvieregge/hask-can-weather#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- text

library:
  source-dirs: src

executables:
  hask-can-weather-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-can-weather

tests:
  hask-can-weather-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-can-weather
